# Generated by Django 5.0 on 2026-02-01 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="comment",
            new_name="reason",
        ),
    ]
