# Generated by Django 5.0 on 2026-02-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_rename_comment_report_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
